# Generated by Django 2.1.7 on 2019-06-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('QQ', models.CharField(max_length=11)),
                ('WX', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tb', models.CharField(max_length=15, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
