# Generated by Django 2.1.7 on 2019-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
