# Generated by Django 2.1.7 on 2019-06-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190607_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='image',
            new_name='img_upload',
        ),
    ]
