# Generated by Django 2.1.7 on 2019-06-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190608_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='img_upload',
            new_name='image',
        ),
    ]
